# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0003_auto_20171130_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
