# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apli', '0006_auto_20171201_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_add3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_edit3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_add2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_edit2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_add5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_edit5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horaire',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_add4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horaire',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_edit4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_add1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_edit1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='time',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_add6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='time',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_edit6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='company_short',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firmakursname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_short',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontaktkursname'),
        ),
    ]
